### Endpoint Test 
GET http://localhost:3003/ping

### Endpoint Get all classrooms 
GET http://localhost:3003/classrooms

### Endpoint Create a new class
POST http://localhost:3003/classrooms
Content-Type: application/json

{
    "name": "Teste3",
    "module": "1"
}

### Endpoint Get active classrooms
GET http://localhost:3003/active/classrooms

### Endpoint Update module classroom
PUT http://localhost:3003/classrooms/102
Content-Type: application/json

{
    "module": "3"
}

### Endpoint Create a new student
POST http://localhost:3003/student
Content-Type: application/json

{
    "name": "teste3",
    "email": "teste3@hotmail.com",
    "birthdate": "1999/04/01",
    "classroomId": "1659035086875"
}

### Endpoint Get student by name, if not pass name returns all students
GET http://localhost:3003/student?q=J

### Endpoint Edit a student's class
PUT http://localhost:3003/student/206
Content-Type: application/json

{
    "newClassroom": "103"
}

### Get All Students Belonging To A Classroom
GET http://localhost:3003/students/103